sudo : required
services:
  - docker
before_install:
  - docker build -t chattyTravis -f Dockerfile . 
# script: to execute test cases
after_success:
  - echo "DOCKER_PASSWD" | docker login -u "$DOCKER_USR" --ppassword=stdin

