sudo: required
language: node_js
install: true
node_js:
  - "8"
services:
  - docker
before_install:
  - docker build -t chatty-travis -f ./Dockerfile .
script:
- echo "skipping tests"
after_success:
  - echo "$DOCKER_PASSWD" | docker login -u "$DOCKER_USR" --password=stdin
  - docker push chatty-travis
