sudo: required
language: node_js
node_js:
  - "8"
services:
  - docker
before_install:
  - docker build -t chatty-travis -f ./Dockerfile .
# script: to execute test cases
after_success:
  - echo "DOCKER_PASSWD" | docker login -u "$DOCKER_USR" --password=stdin
  - docker push chatty-travis
